Feature/ias editor UI
HydrologicEngineeringCenter/HEC-FDA pull request #175
Opened 2021-11-02 17:47 UTC by codymccoy

2021-11-05 21:03 UTC, RyanM-RMA requested changes
Cody, I've finished my review.  For the most part there aren't issues with logic, however there are inconsistency issues (naming, formatting, scoping).  These should be looked into.

There are also some language features we can use to simplify our logic.  We don't necessarily have to use these features as it could increase cognitive complexity, however I do believe we should be learning more about the features.

Some comments can be turned into technical debt tickets for us to review during task 14.

2021-11-08 16:33 UTC, codymccoy commented on FunctionsView/View/CoordinatesFunctionTable.xaml.cs
> +            //foreach(DataGridColumn col in dg_table.Columns)
Done

2021-11-08 16:34 UTC, codymccoy commented on Model/Metrics/IMetricEnum.cs
> +        Default = 5,
Skipping. HEC is replacing the model.

2021-11-08 16:36 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASEditor.xaml.cs
> +        //private void UserControl_Loaded(object sender, RoutedEventArgs e)
done

2021-11-08 16:39 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASEditor.xaml
> +        <!--<Grid x:Name="FifthRowGrid" Grid.Row="5" Margin="5,5,5,0">
done.

2021-11-08 16:41 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASPlotControl.xaml.cs
> +            //_flowFreqChart.SetVerticalChartGroup(guid.ToString());
done.

2021-11-08 16:43 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASPlotControl.xaml.cs
> +        public void Plot()
I changed the method name to "ZoomToExtents". I didn't comment it. It says there are zero references. Is something calling this?

2021-11-08 16:44 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/RecommendationExpanderControl.xaml.cs
> +﻿using System.Windows;
done

2021-11-08 16:45 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/RecommendationExpanderControl.xaml
> +    </UserControl.Resources>
done.

2021-11-08 16:53 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/SpecificIASControl.xaml
> +
done.

2021-11-08 16:55 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/SpecificIASControl.xaml.cs
> +            SpecificIASEditorVM vm = (SpecificIASEditorVM)this.DataContext;
This is probably in 100 different classes. I will not change them all, but will try to us this syntax in the future:
SpecificIASEditorVM vm = DataContext as SpecificIASEditorVM;
            vm?.Plot();

2021-11-08 16:56 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/SpecificIASControl.xaml.cs
> +            SpecificIASEditorVM vm = (SpecificIASEditorVM)this.DataContext;
done.

2021-11-08 17:03 UTC, RyanM-RMA commented on View/ImpactAreaScenario/Editor/IASPlotControl.xaml.cs
> +        public void Plot()
Looks like that used to be called in the VM, go ahead and remove it.

2021-11-08 17:08 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/SpecificIASControl.xaml
> +                    <Button x:Name="addThresholdBtn" Grid.Column="1" Content="Add Additional Thresholds..."  HorizontalAlignment="Stretch" Click="addThresholdBtn_Click"  />
I removed all names.

2021-11-08 17:23 UTC, codymccoy commented on View/Study/StudyView.xaml.cs
>              ViewModel.Study.FdaStudyVM vm = (ViewModel.Study.FdaStudyVM)this.DataContext;
done.

2021-11-08 17:23 UTC, codymccoy commented on View/Study/StudyView.xaml.cs
>              ViewModel.Study.FdaStudyVM vm = (ViewModel.Study.FdaStudyVM)this.DataContext;
done.

2021-11-08 19:14 UTC, codymccoy commented on ViewModel/Study/FDACache.cs
> -            if (childElementType == typeof(IASElement))
great advice. Done.

2021-11-08 19:28 UTC, codymccoy commented on ViewModel/Study/FDACache.cs
> -            if (childElementType == typeof(IASElement))
done.

2021-11-08 19:36 UTC, codymccoy commented on ViewModel/Study/FdaStudyVM.cs
>          public int SelectedTab
Yeah, this class is a bit of a mess but is also a very important class. I deleted most of the commented out code. I don't want to do a deep dive into this class until some of the later tasks that will deal with it directly. Modifications here can have a big impact.

2021-11-08 19:41 UTC, codymccoy commented on View/Study/StudyView.xaml.cs
>          private void btn_TabsView_Click(object sender, RoutedEventArgs e)
done.

2021-11-08 19:46 UTC, codymccoy commented on View/Study/StudyView.xaml.cs
>          private void btn_MapView_Click(object sender, RoutedEventArgs e)
done.

2021-11-08 19:47 UTC, codymccoy commented on View/StageTransforms/RatingCurveEditor.xaml.cs
>              Chart2D chart = new Chart2D(sciChart2DChartViewModel);
done

2021-11-08 19:48 UTC, codymccoy commented on View/Utilities/YearField.xaml.cs
> +        private string combined_text(TextBox tb, string new_text)
done

2021-11-08 19:49 UTC, codymccoy commented on View/Utilities/YearField.xaml.cs
> +
done

2021-11-08 19:49 UTC, codymccoy commented on View/Utilities/YearField.xaml.cs
> +            return s;
done

2021-11-08 19:50 UTC, codymccoy commented on View/Utilities/YearField.xaml.cs
> +            int i;
done.

2021-11-08 21:24 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/ChartControls/ChartControlBase.cs
> +            switch (axis)
This is your code. I will let you deal with this one.

2021-11-08 21:25 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/ChartControls/ChartControlBase.cs
> +            var vm = ChartVM.AxisViewModel as SciChartAxisViewModel;
Your code.

2021-11-08 21:31 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/ChildElementComboItem.cs
> +        public int ID { get; set; } = -1;
I turned the -1 into a constant.

2021-11-08 21:32 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/ChildElementComboItem.cs
> +        private ChildElement _ChildElement;
I am pretty sure it is _Upper but i got so used to rma's style that I think i have been doing a lot of the new stuff as _lower. I will try to always do _Upper.

2021-11-08 21:41 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/IASEditorVM.cs
> +        private Dictionary<ImpactAreaRowItem, SpecificIASEditorVM> _ImpactAreaEditorDictionary;
Done.

2021-11-08 21:46 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/IASEditorVM.cs
> +        private List<ImpactAreaRowItem> _ImpactAreaNames;
done

2021-11-08 21:46 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/IASEditorVM.cs
> +        public ObservableCollection<ChildElementComboItem> ImpactAreaElements { get; set; }
I removed it.

2021-11-08 21:51 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/OverlappingRangeHelper.cs
> +    class OverlappingRangeHelper
done.

2021-11-08 21:52 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/RecommendationRowItem.cs
> +        public List<string> Messages { get; set; }
done.

2021-11-08 23:28 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/SpecificIASEditorVM.cs
> +        private void AddStageDamageElement(object sender, Saving.ElementAddedEventArgs e)
done

2021-11-08 23:39 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/ThresholdRowItem.cs
> +            foreach(ThresholdType tt in ThresholdTypes)
Changed to use linq and got rid of the method altogether.

2021-11-09 13:00 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/IASElementSet.cs
> +            _ViewResults.Header = "View Results";
No reason. I made it local.

2021-11-09 13:39 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/DamageWithUncertaintyVM.cs
>          public SciChart2DChartViewModel ChartViewModel { get; set; } = new SciChart2DChartViewModel("chart title");
How do i handle the loaded event on the xaml.cs class if i get rid of the setter here?

2021-11-09 13:44 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/DamageWithUncertaintyVM.cs
> +            ChartViewModel.LineData.Set(new List<SciLineData>() { _data });
This is now throwing an exception.
![image](https://user-images.githubusercontent.com/47757848/140934869-902e25a7-b4ef-4185-88b2-0b9dd8919345.png)

2021-11-09 13:47 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/Results.cs
> +        public  DamageWithUncertaintyVM DamageWithUncertaintyVM { get; set; }
Removed setters.

2021-11-09 13:48 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/RowItems/EadRowItem.cs
> +        public double Frequency { get; set; }
removed setters.

2021-11-09 13:48 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/RowItems/ResultRowItem.cs
> +        public string Name{get;set;}
removed setters.

2021-11-09 13:50 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/SpecificIASResultVM.cs
> +
How so? Constants should be in all caps with underscores. I think that is the style we use in FDA. Isn't that the same with our java work?

2021-11-09 14:00 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASPlotControl.xaml.cs
> +        public void Plot()
removed.

2021-11-09 14:05 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/SpecificIASResultVM.cs
> +            if (_currentResultVM != null && _currentResultVM is PerformanceVMBase)
Not totally sure what to do here. I removed the null check.

2021-11-09 14:16 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/SpecificIAS.cs
> +                case "NOTSET":
agreed, but this is probably all getting changed when the new model comes in. Not dealing with this now.

2021-11-09 15:44 UTC, codymccoy commented on ViewModel/Utilities/FdaValidationResult.cs
> +        public bool IsValid { get; set; }
I removed the setter and added an _IsValid private variable that gets set internally.

2021-11-09 15:51 UTC, codymccoy commented on ViewModel/Utilities/FdaValidationResult.cs
> +        public FdaValidationResult(bool isValid, string errorMsg)
Lets go over this class and its uses.

2021-11-09 15:55 UTC, codymccoy commented on ViewModel/Study/FDACache.cs
> +        private List<IASElementSet> _IASElementSets = new List<IASElementSet>();
All of these lists?

2021-11-09 17:16 UTC, codymccoy commented on View/Study/StudyView.xaml
> +        <utils:TabControlNoReload  x:Name="DynamicTabControl"  Grid.Row="1" Grid.Column="1" ItemsSource="{Binding TabFactoryInstance.Tabs}"
It is being used, but it doesn't really matter. This whole tab control is going away in a future task.

2021-11-09 17:49 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/SpecificIASResultVM.cs
> +            if (_currentResultVM != null && _currentResultVM is PerformanceVMBase)
done.

2021-11-09 20:43 UTC, codymccoy commented on ViewModel/Utilities/FdaValidationResult.cs
> +        public FdaValidationResult(bool isValid, string errorMsg)
Did a big refactor.

2021-11-09 20:59 UTC, codymccoy commented on View/StageTransforms/RatingCurveEditor.xaml.cs
>              Chart2D chart = new Chart2D(sciChart2DChartViewModel);
Done.

2021-11-09 21:23 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/DamageWithUncertaintyVM.cs
>          public SciChart2DChartViewModel ChartViewModel { get; set; } = new SciChart2DChartViewModel("chart title");
done.

2021-11-09 21:24 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/PerformanceAEPVM.cs
> +            ChartViewModel.LineData.Set(new List<SciLineData>() { _data });
Currently throwing exception.

2021-11-09 21:27 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/PerformanceAEPVM.cs
>              loadDummyData(metrics);
done.

2021-11-09 21:28 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/PerformanceAEPVM.cs
> +        public SciChart2DChartViewModel ChartViewModel { get; set; } = new SciChart2DChartViewModel("chart title");
done.

2021-11-09 22:43 UTC, codymccoy commented on ViewModel/Editors/BaseEditorVM.cs
> +                StudyCache.IASElementAdded += SiblingWasAdded;
I added a ticket in github for this.

2021-11-09 22:43 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/SpecificIASEditorVM.cs
> +            StudyCache.FlowFrequencyAdded += AddFlowFreqElement;
i added a ticket on github.

2021-11-09 22:43 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/DamageWithUncertaintyVM.cs
> +            ChartViewModel.LineData.Set(new List<SciLineData>() { _data });
Ryan will look into this.

2021-11-09 22:44 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Results/PerformanceAEPVM.cs
> +            ChartViewModel.LineData.Set(new List<SciLineData>() { _data });
Ryan will look into this.

2021-11-09 22:46 UTC, codymccoy commented on ViewModel/Study/FDACache.cs
>              if (parentType == typeof(IASOwnerElement))
i added a ticket on github.

2021-11-09 22:47 UTC, codymccoy commented on View/ImpactAreaScenario/Editor/IASPlotControl.xaml.cs
> +        public void Plot()
I removed it.

2021-11-10 19:01 UTC, RyanM-RMA requested changes
Minor changes, I think we can call it good once these are done.

2021-11-10 21:29 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/IASElementSet.cs
> +            Saving.PersistenceFactory.GetIASManager().Remove(this);
done

2021-11-10 21:37 UTC, RyanM-RMA approved these changes

2021-11-10 21:40 UTC, merged