Task 9 import from old fda
HydrologicEngineeringCenter/HEC-FDA pull request #251
Opened 2022-01-25 20:08 UTC by codymccoy

2022-01-31 19:09 UTC, RyanM-RMA requested changes
Got some changes for you

2022-01-31 19:09 UTC, RyanM-RMA commented on ViewModel/Watershed/TerrainElement.cs
>                  Utilities.NamedAction mapWindow = new Utilities.NamedAction();
Remove the unnecessary namespacing

2022-01-31 22:05 UTC, RyanM-RMA approved these changes

2022-01-31 22:06 UTC, merged

2022-01-31 22:06 UTC, RyanM-RMA commented
Issue created to track the requested changes, Cody needs to update task 1 and 2, then fix task 9 changes.

2022-02-07 21:59 UTC, codymccoy commented on Importer/AsciiImportExport/AsciiImport.cs
> +        private AsyncLogger _Logger;
i made it readonly

2022-02-07 22:22 UTC, codymccoy commented on UserControls/TextBoxDescription.xaml
> +        <!--<Button ToolTip="Expand" Style="{StaticResource TransparentStyle}" HorizontalAlignment="right" Margin="0,3,3,0" Name="Expand" VerticalAlignment="Top" Height="18" Width="18" Padding="0">
Leaving for now, we might be adding this back in.