New model integration
HydrologicEngineeringCenter/HEC-FDA pull request #371
Opened 2022-05-25 20:40 UTC by codymccoy

2022-05-30 23:03 UTC, RyanM-RMA requested changes
Few things to resolve, let me know when it's ready

2022-05-31 14:14 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/SpecificIAS.cs
> +        public void ReportMessage(object sender, MessageEventArgs e)
i removed it

2022-05-31 14:17 UTC, codymccoy commented on ViewModel/TableWithPlot/Data/UniformDataProvider.cs
> +        public UniformDataProvider(bool isStrictMonotonic)
Yeah, i wasn't really sure how to handle this one. This is part of the table with plot that HEC wrote and that i copied into FDA. The empty ctor is required for some kind of magic. I defaulted the property and removed the assignment from the empty ctor.

2022-05-31 14:25 UTC, codymccoy commented on ViewModel/ImpactAreaScenario/Editor/SpecificIASEditorVM.cs
> +        public string FrequencyRelationshipLabel { get; } = StringConstants.FREQUENCY_RELATIONSHIP_LABEL;
you will need to show me this one. Can i keep the strings in the VM or do i need to move them into the view?

2022-06-01 16:25 UTC, RyanM-RMA approved these changes

2022-06-01 16:25 UTC, merged