Xml refactor
HydrologicEngineeringCenter/HEC-FDA pull request #490
Opened 2022-08-12 15:22 UTC by codymccoy

2022-08-12 16:41 UTC, rnugent3 commented
Is the unit test no longer relevant?

2022-08-12 16:48 UTC, codymccoy commented
As it turns out, you can't run a unit test that calls into a method that uses MessageBox without it throwing an exception. "BadImageException" if i remember correctly. I looked into how to solve this and there didn't seem to be a simple solution. I would like the message box to be in the method that it is in. I didn't think it was worth the hassle to figure this one out so i commented it out for now. I wrote the reason why above the commented out test.

2022-08-15 19:48 UTC, Brennan1994 requested changes

2022-08-15 20:38 UTC, codymccoy commented on HEC.FDA.ViewModelTest/WriteAndReadToXMLShould.cs
> +        //public void TestStageDamageElementWriteThenReadAreEqual()
In my occtypes_to_xml branch I now have this test working. After working through it, there was a bug between the write and the read from xml.

2022-08-15 20:40 UTC, codymccoy commented on ViewModel/HEC.FDA.ViewModel.csproj
> +  <ItemGroup>
done

2022-08-15 20:58 UTC, codymccoy commented on HEC.FDA.ViewModelTest/WriteAndReadToXMLShould.cs
> +namespace HEC.FDA.ViewModelTest
done

2022-08-15 21:03 UTC, codymccoy commented on HEC.FDA.ViewModelTest/WriteAndReadToXMLShould.cs
> +namespace HEC.FDA.ViewModelTest
I created new classes for the unit tests. The last one that was commented out will be in its own class on my latest branch.

2022-08-15 22:21 UTC, merged