Integration test stage damage
HydrologicEngineeringCenter/HEC-FDA pull request #674
Opened 2022-11-30 00:09 UTC by rtle76

2022-11-30 16:00 UTC, rnugent3 requested changes
This looks good. Please add unit test cases where variation in beginning damage depth results in variation in damage for a given structure.

2022-11-30 16:00 UTC, rnugent3 commented
Once you have those test cases set up, re-request review, and we'll get this branch merged.

2022-12-01 16:24 UTC, rtle76 commented on fda-model-test/unittests/structures/DeterministicStructureShould.cs
> +        [InlineData(100, 0, 0, 999)]
Requested changes made, re-requested pull. Let me know what you think

2022-12-01 20:16 UTC, rnugent3 approved these changes
Really good test cases. Great job, man. Keep it up.

2022-12-01 20:17 UTC, merged