852 analytical frequency curve should plot on normal probability axis
HydrologicEngineeringCenter/HEC-FDA pull request #858
Opened 2023-04-06 22:03 UTC by Brennan1994

2023-04-06 22:04 UTC, Brennan1994 commented
This does not fully address the issue of confidence limits yet. It applies them in one location, and adds the model logic to compute them.

2023-04-08 19:06 UTC, rnugent3 commented on HEC.FDA.ModelTest/unittests/extensions/ContinuousDistributionExtensionsShould.cs
> +        //https://www.hec.usace.army.mil/confluence/sspdocs/ssptutorialsguides/expected-moments-algorithm-study-guide/user-defined-functions-for-lpiii-and-gev-frequency-curves#UserDefinedFunctionsfor
cool!

2023-04-08 19:12 UTC, rnugent3 commented
I ran into an uncaught exception 

![image](https://user-images.githubusercontent.com/25163165/230738837-e5c9c6ea-b896-4a85-bf4d-0ae0e9ba6af7.png)

2023-04-08 19:13 UTC, rnugent3 commented
The exception happens when I attempt to view a graphical frequency function.

2023-04-08 19:19 UTC, rnugent3 requested changes
Please troubleshoot the overflow exception.

2023-04-10 21:19 UTC, Brennan1994 commented
The latest update updates the tracker to use the probability rather than the Z score, so you can check exact probabilities anywhere on the lines. 

I was unable to reproduce your error. Please send me your dataset if that's still an issue.

2023-04-10 22:29 UTC, rnugent3 approved these changes
terrific

2023-04-10 22:29 UTC, merged